name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: akhileshns/heroku-deploy@v3.0.5
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "twitter-api-clone-1"
          heroku_email: "wshehzad111@gmail.com"
